### PR TITLE
Bump Visual Studio Tools for Unity changelog to 3.1.0.0

### PR DESCRIPTION
**Pull request by sailro**

### CODE REVIEW

**Comment by sailro** [comment]
cc @jbevain @TerryGLee

**Comment by sailro** [comment]
We'll be able to publish the bits this morning, so we could change the date to 4/6

**Comment by TerryGLee** [comment]
Let's publish it as is and if we want, we can change the date to 4/6/2017 after-the-fact.

**Comment by sailro** [comment]
Bits are live

**Pull request merged**
